#!/bin/sh

TEST="$1"

echo "Actual output:\n---------------------------------"
./sdriver.pl -t test$TEST.in -s ../tsh
echo "Predictied output:\n---------------------------------"
./sdriver.pl -t test$TEST.in -s ./tsh-orig

